[package]
authors = ["Jason Lee <huacnlee@gmail.com>"]
categories = ["compile-time", "localization", "internationalization"]
description = "Rust I18n is use Rust codegen for load YAML file storage translations on compile time, and give you a t! macro for simply get translation texts."
edition = "2018"
exclude = ["examples", "crates", "tests"]
keywords = ["i18n", "yml", "localization", "internationalization"]
license = "MIT"
name = "rust-i18n"
readme = "README.md"
repository = "https://github.com/longbridgeapp/rust-i18n"
version = "0.2.0"

[dependencies]
lazy_static = "1.4.0"
rust-i18n-support = {path = "./crates/support", version = "0.2"}

[dev-dependencies]
foo = {path = "examples/foo"}
